### ISSUE TITLE
I am getting this weird error.

### ISSUE THREAD

**Issue by JakobRinke** [ThatsJustBonkers/RandomRGOVictoria2#1]
My settings are completly random (1, 1) 

1680 - Fez.txt
Traceback (most recent call last):
  File "randomprovincemain.py", line 211, in <module>
    main()
  File "randomprovincemain.py", line 198, in main
    completeRandom(techInput)
  File "randomprovincemain.py", line 40, in completeRandom
    tag = changeProvince.create_province()
  File "C:\Users\____\Downloads\RandomRGOVictoria2-main\RandomRGOVictoria2-main\randomclass.py", line 26, in create_province
    tag = findTag(line.strip())
  File "C:\Users\____\Downloads\RandomRGOVictoria2-main\RandomRGOVictoria2-main\randomclass.py", line 130, in findTag
    tag = line.removeprefix("owner = ")
AttributeError: 'str' object has no attribute 'removeprefix
`

**Comment by Eake123** [comment]
Ok I see the problem. I'll send you the fixed version once I'm done work. 

If possible could you send me a screenshot of 1680 fez.txt it should be in history > provinces

**Comment by JakobRinke** [comment]
owner = MOR
controller = MOR
add_core = MOR
trade_goods = grain
life_rating = 35

**Comment by Eake123** [comment]
Ok I changed the logic in the line you were getting an error in. I only made a change to randomclass.py so you dont have to download the other file. Since I've never encountered that error I'm not sure if my fix will help but fingers crossed. If it doesn't fix it send me another comment.

**Comment by JakobRinke** [comment]
thank you, I got it to work
